services:
  - type: web
    name: thermo-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir my-app-thermo app:app"
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
